name: Deploy CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm install
      - name: Generate ImHex
        run: |
          mkdir -p imhex/includes
          node generators/imhex-generator.js
      - name: Generate Kaitai
        run: |
          mkdir -p kaitai/bl61x kaitai/bl808
          node generators/kaitai-generator.js
      - name: Upload ImHex artifacts
        uses: actions/upload-artifact@v3
        with:
          name: imhex-hexpats
          path: |
            imhex
          if-no-files-found: error
      - name: Upload Kaitai artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kaitai-ksy
          path: |
            kaitai
          if-no-files-found: error 
