name: Deploy CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Generate ImHex
        run: |
          npm install
          mkdir -p imhex/includes
          node generators/imhex-generator.js
      - name: Upload ImHex artifacts
        uses: actions/upload-artifact@v2
        with:
          name: imhex-hexpats
          path: |
            imhex
          if-no-files-found: error 